default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: desafio_orcamento_development

test:
  <<: *default
  database: desafio_orcamento_test
  
production:
  <<: *default
  database: desafio_orcamento_production
  username: desafio_orcamento
  password: <%= ENV["DESAFIO_ORCAMENTO_DATABASE_PASSWORD"] %>
